services:
  - type: web
    name: interview-voice-bot-backend
    runtime: node
    buildCommand: cd server && npm install
    startCommand: node server/server.js
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    healthCheckPath: /health

  - type: static_site
    name: interview-voice-bot-frontend
    buildCommand: cd client && npm install && npm run build
    outputDirectory: client/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://interview-voice-bot-backend.onrender.com
    plan: free
